// <auto-generated />
namespace TaxiteBus.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class prenom : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(prenom));
        
        string IMigrationMetadata.Id
        {
            get { return "201703110504459_prenom"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
